apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: httpmqapp
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-QECF-MBXVLU
    use: CloudPakForIntegrationNonProductionFREE
  flowType:
    toolkitFlow: true
  forceFlowsHTTPS:
    enabled: true
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 300m
              memory: 368Mi
          name: runtime
          image: 'image-registry.openshift-image-registry.svc:5000/cp4i/httpmqapp:v1'
  logFormat: basic
  configurations:
    - httpmqapp-mqpolicy
  defaultNetworkPolicy:
    enabled: true
  replicas: 1
  version: 12.0.12.0-r2