apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: Production
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
  queueManager:
    name: QM1
    mqsc:
      - configMap:
          items:
            - defs-v1
          name: qm1-definitions
    storage:
      queueManager:
        type: persistent-claim
  template:
        pod:
          containers:
            - name: qmgr
              env:
              - name: MQSNOAUT
                value: 'yes'
  version: 9.3.5.1-r2