apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: nha-qm1
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: Production
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
  queueManager:
    mqsc:
      - configMap:
          items:
            - queues-v1.mqsc
          name: nha-qm1
    availability:
      type: NativeHA
      updateStrategy: RollingUpdate
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: ocs-storagecluster-ceph-rbd
  version: 9.3.5.1-r2
