apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qm2-ibm-mq-test-app-svrconn
spec:
  host: rfhutil2e-svrconn.chl.mq.ibm.com
  to:
    kind: Service
    name: qm2-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough