apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm-1
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  web:
    enabled: true
  version: 9.2.5.0-r3
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: "yes"
          name: qmgr
  securityContext:
    initVolumeAsRoot: false
    supplementalGroups:
      - 99
  queueManager:
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    name: QM1
    mqsc:
      - configMap:
          items:
            - config.mqsc
          name: mq-mqsc
    availability:
      type: SingleInstance
    storage:
      defaultClass: ocs-storagecluster-cephfs
      queueManager:
        class: ocs-storagecluster-cephfs
        type: persistent-claim
